name: Harness Triggered Pipeline

on:
  repository_dispatch:
    types: [webhook-event]  # <--- CHANGED: Matches your JSON "event_type"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Script
        run: |
          echo "Triggered by Harness!"
          
          # accessing the new JSON fields
          echo "Message: ${{ github.event.client_payload.message }}"
          echo "Environment: ${{ github.event.client_payload.env }}"
